version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/tetafro/tags
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test ./...
  codecov:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/tetafro/tags
    steps:
      - checkout
      - run: ./.circleci/codecov.sh
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  main:
    jobs:
      - test
      - codecov:
          requires:
            - test
